name: Alpine Linux 64-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Alpine Linux 64-bit
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apk
          key: ${{ runner.os }}-alpine64-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-alpine64-deps-

      - name: Set up build environment
        run: |
          apk add --no-cache cmake make gcc g++ musl-dev gcompat libc6-compat dos2unix file

      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/scripts"
          dos2unix run_tests.sh
          chmod +x run_tests.sh
          export ARCH="x64"
          /bin/sh run_tests.sh --arch x64
