name: Fedora 64-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Fedora 64-bit
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/dnf
          key: ${{ runner.os }}-fedora64-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-fedora64-deps-

      - name: Set up build environment
        run: |
          dnf install -y cmake gcc gcc-c++ make

      - name: Run tests
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/run_tests.sh"
          export ARCH="x64"
          "$GITHUB_WORKSPACE/scripts/run_tests.sh" --arch x64
