name: macOS 32-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on macOS 32-bit
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-macos32-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-macos32-deps-

      - name: Set up 32-bit environment
        run: |
          brew install cmake
          # Note: macOS does not natively support 32-bit builds anymore. This may require additional setup.

      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh
