name: macOS 32-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on macOS 32-bit
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-macos32-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-macos32-deps-

      - name: Set up 32-bit environment
        run: |
          brew install cmake
          # Note: Modern macOS versions don't support 32-bit binaries anymore
          echo "::warning::macOS 32-bit support is deprecated and may not work on modern systems"

      - name: Run tests
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/run_tests.sh"
          export ARCH="x86"
          "$GITHUB_WORKSPACE/scripts/run_tests.sh" --arch x86
