name: Linux Mint 64-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Linux Mint 64-bit
    runs-on: ubuntu-latest
    container: linuxmintd/mint20.3:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-mint64-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-mint64-deps-

      - name: Set up build environment
        run: |
          apt-get update
          apt-get install -y cmake build-essential

      - name: Run tests
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/run_tests.sh"
          export ARCH="x64"
          "$GITHUB_WORKSPACE/scripts/run_tests.sh" --arch x64
