name: Linux Mint 32-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Linux Mint 32-bit
    runs-on: ubuntu-latest
    container: linuxmintd/mint20.3:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-mint32-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-mint32-deps-

      - name: Set up 32-bit environment
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install -y cmake build-essential gcc-multilib g++-multilib libc6-dev-i386

      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          export ARCH="x86"
          ./scripts/run_tests.sh --arch x86
