name: Ubuntu 32-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Ubuntu 32-bit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            /var/cache/apt/archives
          key: ${{ runner.os }}-ubuntu32-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ubuntu32-deps-

      - name: Set up 32-bit environment
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-multilib g++-multilib libc6-dev-i386

      - name: Run tests
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/run_tests.sh"
          export ARCH="x86"
          "$GITHUB_WORKSPACE/scripts/run_tests.sh" --arch x86
