name: Ubuntu 64-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Ubuntu 64-bit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            /var/cache/apt/archives
          key: ${{ runner.os }}-ubuntu64-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ubuntu64-deps-

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Run tests
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/run_tests.sh"
          export ARCH="x64"
          "$GITHUB_WORKSPACE/scripts/run_tests.sh" --arch x64
