name: Ubuntu 32-bit Testing

on:
  push:
    branches: ["main", "develop", "ci"]
  pull_request:
    branches: ["main", "develop", "ci"]

jobs:
  test:
    name: Test on Ubuntu 32-bit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up 32-bit environment
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-multilib

      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh
